"""
Partially generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install langchain
# !pip install google-search-results

# https://www.youtube.com/watch?v=kYRB-vJFy38&list=PLqZXAkvF1bPNQER9mLmDbntNfSpzdDIU5&index=2

from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

import os
os.environ['SERPAPI_API_KEY'] = userdata.get('SERPAPI_API_KEY')

from langchain.llms import OpenAI
from langchain.agents import load_tools, initialize_agent

llm = OpenAI(
    openai_api_key=OPENAI_API_KEY,
    model_name='gpt-3.5-turbo-instruct',
    temperature=0.1
)

tools = load_tools(
    llm=llm,
    tool_names=['serpapi', 'llm-math'],
)

agent = initialize_agent(
    tools,
    llm,
    agent='zero-shot-react-description',
    verbose=True, # show what it's thinking
)

agent.run('Who is the current leader of Japan and their age? What is the largest prime number that is smaller than their age?')

"""
> Entering new AgentExecutor chain...
 I should use a search engine to find the current leader of Japan and their age, and then use a calculator to find the largest prime number smaller than their age.
Action: Search
Action Input: "current leader of Japan"
Observation: Fumio Kishida is the current prime minister of Japan, replacing Yoshihide Suga on 4 October 2021. As of 24 January 2024, there have been 64 individual prime ministers serving 101 terms of office.
Thought: Now I need to find the age of Fumio Kishida.
Action: Search
Action Input: "Fumio Kishida age"
Observation: 66 years
Thought: I can use a calculator to find the largest prime number smaller than 66.
Action: Calculator
Action Input: 66
Observation: Answer: 66
Thought: Wait, 66 is not a prime number. I need to subtract 1 and keep subtracting until I get a prime number.
Action: Calculator
Action Input: 66-1=65
Observation: Answer: True
Thought: 65 is a prime number. I now know the largest prime number smaller than Fumio Kishida's age.
Final Answer: The largest prime number smaller than Fumio Kishida's age is 65.

> Finished chain.
The largest prime number smaller than Fumio Kishida's age is 65.
"""
