"""
Partially generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install langchain
# !pip install openai

from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

from langchain.llms import OpenAI

openai = OpenAI(openai_api_key=OPENAI_API_KEY, model_name="gpt-3.5-turbo-instruct")
result = openai("Translate 'Hello, world!' into French.")
print(result)
