"""
Partially generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install openai
# !pip install langchain

from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate

llm = OpenAI(
    openai_api_key=OPENAI_API_KEY,
    model_name='gpt-3.5-turbo-instruct',
)

promptMaker = PromptTemplate(
    template='What are 5 of the most famous {what}?',
    input_variables=['what'],
)

prompt = promptMaker.format(what='conlangs')
print(prompt)

response = llm(prompt)
print(response)
